[package]
name = "stun"
version = "0.1.0"
authors = ["mchlrhw <4028654+mchlrhw@users.noreply.github.com>"]
edition = "2018"

[dependencies]
crc = "1.8"
fehler = "1.0"
nom = "5"
rust-crypto = "0.2"
rand = "0.7"
thiserror = "1.0"
