[package]
name = "sdp"
version = "0.1.0"
authors = ["mchlrhw <4028654+mchlrhw@users.noreply.github.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
nom = "5"
nom_locate = { git = "https://github.com/fflorent/nom_locate.git" }
