version: 2.1

commands:
  setup_sccache:
    steps:
      - run:
          name: Setup sccache
          command: |
            cargo install sccache
            echo 'export "RUSTC_WRAPPER"="sccache"' >> $BASH_ENV
            echo 'export "SCCACHE_CACHE_SIZE"="1G"' >> $BASH_ENV
            sccache --version
  restore_sccache:
    steps:
      - restore_cache:
          name: Restore cache
          key: sccache-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
  run_lint_and_test:
    steps:
      - run:
          name: Tool versions
          command: |
            rustc --version
            cargo --version
            rustup --version
      - run:
          name: Format
          command: |
            rustup component add rustfmt
            cargo fmt -- --check
      - run:
          name: Lint
          command: |
            rustup component add clippy
            cargo clippy --all -- -D warnings
      - run:
          name: Test
          command: cargo test
  save_sccache:
    steps:
      - save_cache:
          name: Save cache
          key: sccache-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - "~/.cache/sccache"

jobs:
  run_tests:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - setup_sccache
      - restore_sccache
      - run_lint_and_test
      - save_sccache

workflows:
  version: 2
  run_tests:
    jobs:
      - run_tests
