[package]
name = "webrtc"
version = "0.1.0"
authors = ["mchlrhw <4028654+mchlrhw@users.noreply.github.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.2"
failure = "0.1.5"
log = "0.4.7"
rand = "0.7.0"
sdp = { path = "../sdp" }
pnet = "0.22.0"
